#testing: true

# Site settings
title: "The 12th Brauer group conference"
description: "8-12 June, 2015, at Pingree Park Colorado"

baseurl: ""

# url: "localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
