#testing: true

# Site settings
title: "The 13th Brauer group conference"
description: "June, 2018, at Pingree Park Colorado"

baseurl: "/brauer"

# url: "localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
